### PR TITLE
Antidote stats

### PR DESCRIPTION
**Pull request by slimfire**
- Refactored influxDB functions into Antidote-Stats Program
- Updated data format on TSDBExport to capture `lessonId`, `lessonName`, `syringeTier`, `error`, `healthyTests`, `totalTests`, `lessonStage` and `createdTime` on each liveLesson periodically
- Added tests on StartTSDBExport and RecordProvisioningTime

### CODE REVIEW

**Comment by Mierdin** [comment]
The code here can be reasonably self-contained, so instead of a dedicated `stats` package, I'm thinking we can just put everything in `cmd/antidote-stats/*`

**Comment by slimfire** [comment]
Ok, I'll put it in `cmd/antidote-state/*`

**Comment by Mierdin** [comment]
Have you thought about how you want to add tests? Looks like you started with `cmd/antidote-stats/stats_test.go` but that just contains the helper functions for assertions. I'd like to at least maintain equivalent (or better, preferably) test coverage ratio, especially for all new code.

**Comment by slimfire** [comment]
Ok, let me look into it

**Comment by slimfire** [comment]
@Mierdin thanks for reviewing. In general, there is room for improvement but I've added tests and the coverage will now increase by 3.79%

**Comment by Mierdin** [comment]
@slimfire Hey, just wanted to send a note and let you know I haven't forgotten about this. I have changed my mind on a few things in the past few months, and one of these things is the need to break things into separate processes. There are some discoveries I've made in #141, and after revisiting the way that Antidote handles its own internal state, I'm finding that a monolithic approach **may** end up being simpler and easier to manage, which is obviously the goal.

I'm still motivated to re-think the way we're publishing stats, and would love for you to be involved in that - so I'd ask for your patience while work out how to simplify things further and give us a good base to add things on top of that makes the project more maintainable long-term.

Thanks!

**Comment by Mierdin** [comment]
I had a chance to look at this again now that #141 is merged. I encourage you to take a look at the result from that PR - stats is still its own service, but run as a top-level goroutine alongside the scheduler and API. I know previously we talked about breaking stats into its own separate process, but I think this is a better way to go. I do still think that we should get cleaner about the stats that we're exporting.

One thing I'm confused about - it looks like you've brought in a large number of files into this PR. From looking at them, it seems you've copied the NRE labs curriculum directory into a testdata directory. I imagine this was done in the course of building tests for this package. We can't do this, however; I fear I wasn't clear about what I was thinking previously. I'll spend some time now explaining in some detail what I think the next steps should be.

The main problem with the stats package since the inception of the project is that I haven't had a chance to sit down and really think about a) what stats we're exporting and b) how we're going about collecting them, and c) that we're exporting them in a way that makes sense. Much of the code in that package today is as it was when we first started. Given that #141 is now merged, it's really the last portion of the codebase that hasn't been given this TLC.

However, I don't view this as a gargantuan effort. To me, this involves three things:
- Updating the existing fields and tags where it makes sense
- Re-thinking the functional surface of the package
- Implementing simple tests (really no more than a single `stats_test.go` file)

Now that the stats service is running in response to NATS messages, I would also be interested in hearing ideas for what other kinds of internal events we can export stats for. Right now, the stats service is only listening for finished lesson events to track startup time, but I imagine there could be others.

I am not comfortable merging this PR as it stands now, so the way I see it, we could go one of two ways:
- Close this PR, and start from a more recent `master`.
- You could try to merge the latest changes from `master`, but I imagine you'll run into some conflicts. I would also prefer that you remove the testdata directory - this PR really should result in no more than ~3 files changed, IMO.

Hope that was helpful and clearer than before. Let me know which direction you'd like to go. Thanks!

**Comment by slimfire** [comment]
Hey Matt, ok. Will look at it. Thanks

**Comment by Mierdin** [comment]
Closing due to inactivity, and also due to the outdated nature of this branch. If you wish to resume this work in the future per the comments above, please open a new PR.

**Pull request closed without merging**
